Movie_Ticket_Booking/Models/Actor.cs
using System.ComponentModel.DataAnnotations;

namespace Movie_Ticket_Booking.Models
{
    public class Actor
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(length: 30)]
        [MinLength(3)]
        public string Name { get; set; } = string.Empty;
        [MaxLength(1000)]
        [MinLength(10)]
        public string? Bio { get; set; }
        public string? ProfilePictureURL { get; set; }
        // Relationships
        public List<Movie> Movies { get; set; } = new List<Movie>();


    }
}

Movie_Ticket_Booking/Areas/Admin/Controllers/ActorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movie_Ticket_Booking.DataAccess;
using Movie_Ticket_Booking.Models;
using Movie_Ticket_Booking.Repositories;
using Movie_Ticket_Booking.Repositories.IRepositories;
using Movie_Ticket_Booking.Utitlies;
using System.Threading;
using System.Threading.Tasks;

namespace Movie_Ticket_Booking.Areas.Admin.Controllers
{
    [Area(areaName: "Admin")]
    [Authorize(Roles = $"{SD.SUPER_ADMIN_ROLE},{SD.ADMIN_ROLE},{SD.EMPLOYEE_ROLE}")]


    public class ActorController : Controller
    {
        private readonly IRepository<Actor> _actorRepository;

        public ActorController(IRepository<Actor> actorRepository)
        {
            _actorRepository = actorRepository;
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var actors = await _actorRepository.GetAsync(tracked: false, cancellationToken: cancellationToken);

            return View(actors);
        }

        public IActionResult Create()
        {

            return View(new Actor());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Actor actor, IFormFile photo, CancellationToken cancellationToken)
        {
            if (photo is not null)
            {

                var photoName = Guid.NewGuid().ToString() + Path.GetExtension(photo.FileName);
                var photoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\assets\\img\\photo", photoName);
                using (var stream = System.IO.File.Create(photoPath))
                {
                    photo.CopyTo(stream);
                }

                actor.ProfilePictureURL = "/assets/img/photo/" + photoName;
            }

            if (ModelState.IsValid)
            {
                await _actorRepository.AddAsync(actor, cancellationToken);
                await _actorRepository.CommitAsync(cancellationToken);
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
        [Authorize(Roles = $"{SD.SUPER_ADMIN_ROLE},{SD.ADMIN_ROLE}")]
        public async Task<IActionResult> Edit(int id, CancellationToken cancellationToken)
        {
            var actor = await _actorRepository.GetOneAsync(e => e.Id == id, cancellationToken: cancellationToken);

            if (actor is null)
            {
                return NotFound();
            }
            return View(actor);
        }
        [HttpPost]
        [Authorize(Roles = $"{SD.SUPER_ADMIN_ROLE},{SD.ADMIN_ROLE}")]
        public async Task<IActionResult> Edit(Actor actor, IFormFile? photo, CancellationToken cancellationToken)
        {
            var existingActor = await _actorRepository.GetOneAsync(e => e.Id == actor.Id, cancellationToken: cancellationToken);

            if (existingActor is null)
                return NotFound();


            if (photo is not null)
            {
                var photoName = Guid.NewGuid().ToString() + Path.GetExtension(photo.FileName);
                var photoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\assets\\img\\photo", photoName);
                using (var stream = System.IO.File.Create(photoPath))
                {
                    photo.CopyTo(stream);
                }

                if (existingActor.ProfilePictureURL is not null)
                {
                    var oldPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\assets\\img\\photo", existingActor.ProfilePictureURL);
                    if (System.IO.File.Exists(oldPath))
                    {
                        System.IO.File.Delete(oldPath);
                    }
                }

                existingActor.ProfilePictureURL = "/assets/img/photo/" + photoName;
            }
            if (ModelState.IsValid)
            {
                existingActor.Name = actor.Name;
                existingActor.Bio = actor.Bio;

                await _actorRepository.CommitAsync(cancellationToken);
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
        [Authorize(Roles = $"{SD.SUPER_ADMIN_ROLE},{SD.ADMIN_ROLE}")]

        public async Task<IActionResult> Delete(int id,CancellationToken cancellationToken)
        {
            var actor = await _actorRepository.GetOneAsync(e => e.Id == id, cancellationToken: cancellationToken);

            if (actor is not null)
            {
                _actorRepository.Delete(actor);
                await _actorRepository.CommitAsync(cancellationToken);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Movie_Ticket_Booking/Areas/Admin/Views/Actor/Create.cshtml
@model Actor

@{
    ViewData["Title"] = "Create Actoe";
}

<div class="container my-4">
    <div class="card shadow-sm border-0">
        <div class="card-body">
            <h3 class="mb-4"><i class="bi bi-plus-circle"></i> Add New Actor</h3>

            <form asp-action="Create" asp-controller="Actor" asp-area="Admin" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                <div class="mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Bio" class="form-label"></label>
                    <textarea asp-for="Bio" class="form-control"></textarea>
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="ProfilePictureURL" class="form-label">Upload Photo</label>
                    <input class="form-control" type="file" name="photo" placeholder=" Choose photo" />

                </div>

                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Movie_Ticket_Booking/Areas/Admin/Views/Actor/Edit.cshtml
@model Actor

@{
    ViewData["Title"] = "Edit Actoe";
}

<div class="container my-4">
    <div class="card shadow-sm border-0">
        <div class="card-body">
            <h3 class="mb-4"><i class="bi bi-plus-circle"></i> Edit Actor</h3>

            <form asp-action="Edit" asp-controller="Actor" asp-area="Admin" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                <div class="mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Bio" class="form-label"></label>
                    <textarea asp-for="Bio" class="form-control"></textarea>
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                @if (Model.ProfilePictureURL is not null)
                {
                <div class="mb-3 text-center">
                    <label class="form-label fw-bold">Current photo</label><br />
                    <img src="@Model.ProfilePictureURL" alt="Current photo" width="150" height="150" style="object-fit: cover; border-radius: 10px; border: 1px solid #ccc;" />
                </div>
                }
                <div class="mb-3">
                    <label asp-for="ProfilePictureURL" class="form-label">Upload Photo</label>
                    <input class="form-control" type="file" name="photo" placeholder=" Choose photo" />

                </div>
                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Movie_Ticket_Booking/Areas/Admin/Views/Actor/Index.cshtml
@using Movie_Ticket_Booking.Utitlies
@model IEnumerable<Actor>

@{
    ViewData["Title"] = "Movie Actors";
}
<div class="my-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="m-0"><i class="bi bi-film"></i> Actors</h2>
        <a asp-area="Admin" asp-controller="Actor" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Add New Actor
        </a>
    </div>
    <div class="table-responsive scrollbar">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Bio</th>
                    <th scope="col">Photo</th>
                    <th class="text-end" scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            <tbody>
            <tbody>
            <tbody>
                @foreach (var actor in Model)
                {
                    <tr>
                        <td>@actor.Name</td>
                        <td>@actor.Bio</td>
                        <td>
                            <img src="@actor.ProfilePictureURL" height="80" style="object-fit: cover; border-radius: 10px;" />
                        </td>
                        <td class="text-end">
                            @if (User.IsInRole(SD.SUPER_ADMIN_ROLE) || User.IsInRole(SD.ADMIN_ROLE))
                            {
                                <a href="/Admin/Movie/Edit/@actor.Id" class="btn btn-link p-0" data-bs-toggle="tooltip" title="Edit">
                                    <span class="text-500 fas fa-edit"></span>
                                </a>
                                <a href="/Admin/Movie/Delete/@actor.Id" class="btn btn-link p-0 ms-2" data-bs-toggle="tooltip" title="Delete">
                                    <span class="text-500 fas fa-trash-alt"></span>
                                </a>
                            }
                            else
                            {
                                <span class="text-muted">No Actions!</span>
                            }
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>